FROM ubuntu:20.04

# Defina o fuso horário e torne a configuração não interativa
ENV DEBIAN_FRONTEND=noninteractive

RUN ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
    apt-get update && apt-get install -y tzdata && \
    dpkg-reconfigure --frontend noninteractive tzdata

# Instala o Apache, PHP e extensões necessárias
RUN apt-get update && apt-get install -y \
    apache2 \
    libapache2-mod-php7.4 \
    php7.4 \
    php7.4-mysql \
    php7.4-mbstring \
    php7.4-xml \
    php7.4-curl \
    php7.4-json \
    php7.4-zip \
    && apt-get clean

# Copia o código do projeto para o diretório raiz do Apache
COPY ./public_html /var/www/html/

COPY ./php.ini /usr/local/etc/php/php.ini

COPY myapp.conf /etc/apache2/sites-available/myapp.conf

COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

COPY ./dnsmasq.conf /etc/dnsmasq.conf

COPY ./hosts /etc/hosts

# Copia o script de inicialização
COPY init.sh /init.sh

RUN chmod +x /init.sh

# Exponha a porta 80 para o Apache
EXPOSE 80

# Habilita o módulo rewrite
RUN a2enmod rewrite

RUN a2ensite myapp.conf

RUN a2dissite 000-default.conf



# Define o script de inicialização como o comando padrão
CMD ["/init.sh"]

